title: Márton Lente - Brand, design and development
author:
  name: Márton Lente
  email: 'contact@martonlente.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
    og:type: 'website'
    og:site_name: 'Márton Lente - Brand, design and development'

redirects:
  /en/about/index.html: '/about'
  /en/blog/choosing-hardware-wisely-for-architectural-visualization: '/blog/choosing-hardware-wisely-for-architectural-visualization'
  /en/blog/choosing-video-card-wisely-for-high-end-architectural-visualization-work: '/blog/choosing-video-card-wisely-for-high-end-architectural-visualization-work'
  /en/blog/launching-my-blog-on-arch-viz-and-web-design-and-development: '/blog/launching-my-blog-on-arch-viz-and-web-design-and-development'
  /en/blog/making-career-portal-and-web-design-and-development-for-studio-in-ex-zrt-case-study-part-1: '/blog/making-career-portal-and-web-design-and-development-for-studio-in-ex-zrt-case-study-part-1'
  /en/blog/migrating-from-3ds-max-to-cinema-4d-in-professional-arch-viz-part-1: '/blog/migrating-from-3ds-max-to-cinema-4d-in-professional-arch-viz-part-1'
  /en/blog/mobilizing-your-professional-arch-viz-production-environment-without-compromises: '/blog/mobilizing-your-professional-arch-viz-production-environment-without-compromises'
  /en/blog/the-benefits-of-choosing-perch-cms-against-wordpress-as-your-websites-content-management-system: '/blog/the-benefits-of-choosing-perch-cms-against-wordpress-as-your-websites-content-management-system'
  /en/blog: '/blog'
  /en/branding/index.html: '/brand-design'
  /en/branding: '/brand-design'
  /en/contact-me/index.html: '/'
  /en/index.html: '/'
  /en/my-work/3h-architecture-custom-designed-website-development.html: '/work/3h-architecture-custom-designed-website-development'
  /en/my-work/apartment-at-garay-square-creative-interior-visualization.html: '/work/apartment-at-garay-square-creative-interior-visualization'
  /en/my-work/apartment-in-kazmer-street-interior-visualization.html: '/work'
  /en/my-work/apartment-in-veres-palne-street-interior-visualization.html: '/work'
  /en/my-work/bimcap-brand-design-web-design-and-web-development.html: '/work/bimcap-brand-design-web-design-and-web-development'
  /en/my-work/business-website-and-career-portal-design-and-web-development-for-studio-in-ex-zrt.html: '/work/business-website-and-career-portal-design-and-web-platform-development-for-development-for-studio-in-ex-zrt'
  /en/my-work/clubhouse-for-therapeutic-horse-riding-center-visualization.html: '/work'
  /en/my-work/custom-designed-webportal-development-for-loffice.html: '/work/custom-designed-webportal-development-for-loffice'
  /en/my-work/custom-designed-website-development-for-archinest.html: '/work/custom-designed-website-development-for-archinest'
  /en/my-work/custom-designed-website-development-for-studio-storiz.html: '/work/custom-designed-website-development-for-studio-storiz'
  /en/my-work/family-house-in-hegyalja-street-architectural-visualization.html: '/work'
  /en/my-work/hans-wegner-furniture-product-visualization-studies.html: '/work'
  /en/my-work/index.html: '/work'
  /en/my-work/landing-page-design-and-bespoke-wordpress-website-building-for-3fprojects-retail-lighting-service.html: '/work/landing-page-design-and-bespoke-wordpress-website-building-for-3f-projects-retail-lighting-service'
  /en/my-work/luxury-apartment-at-kolto-street-creative-interior-visualization.html: '/work'
  /en/my-work/moroso-klara-armchair-3d-modeling-furniture-product-visualization-studies.html: '/work'
  /en/my-work/personal-brand-design-web-design-and-web-development.html: '/work/personal-brand-design-web-design-and-web-development'
  /en/my-work/residential-house-in-temesvar-street-visualization.html: '/work'
  /en/my-work/residential-house-in-ulaszlo-street-visualization.html: '/work'
  /en/my-work/residential-house-renovation-at-kelenhegyi-street-visualization.html: '/work'
  /en/my-work/restaurant-la-nonna-at-heviz-hotel-aquamarin-interior-design-visualization.html: '/work/restaurant-la-nonna-at-heviz-hotel-aquamarin-interior-design-visualization'
  /en/my-work/sa43-residential-house-at-stromfeld-aurel-street-visualization.html: '/work'
  /en/my-work/sample-case-study-house-in-sweden-architectural-visualization.html: '/work/sample-case-study-house-in-sweden-architectural-visualization'
  /en/my-work/themed-accomodations-at-zebegeny-architectural-visualization.html: '/work'
  /en/my-work/web-design-and-web-development-for-comeouttriumphant-org.html: '/work/making-custom-web-design-and-web-development-for-comeouttriumphant-org'
  /en/my-work/web-design-and-web-development-for-ml2s-sustainable-solutions.html: '/work/web-design-and-web-development-for-ml2s-sustainable-solutions'
  /en/my-work/web-design-and-web-development-for-schuller-es-tarsai-design-studio.html: '/work/web-design-and-web-development-for-schuller-es-tarsai-design-studio'
  /en/web-design-and-development/index.html: '/development'
  /en/web-design-and-development: '/development'
  /en: '/'
